language: generic
sudo: required
services:
  - docker
env:
  matrix:
  - IMAGE=go-dep/1.11
  - IMAGE=vuepress
  global:
  # DOCKER_EMAIL
  - secure: i+Jx5CN6ulK1F9QN86Ss79uWaQJqoCYhxVvpbxzFM5qlQ5nFJLMh6KKOrn1+9qq5ij97LIVtj6aLB5JWxf3OrKwKIECHfSRjsnnHZbZ/OZXFK1DpHA8djh3TpA4XLgtg1pszwKn9xep4esYfHO2FT9fiA9MVFFgLU8wwgq64gSnSPI7PKuNjlHVyV2K4OMCnsPhQ+FI/d3iLWW/1PIJejPsNzw1lEEgPWPP0gEwOngU8au7uzjnjNny8jHgoVyzaEBh5Ab3r16yFBlVU2AqAlfGjPk+Fg+HQTK4nw0wZjyJ5WgkARBC3lPpxsk0KhqXE66wBlBOHGBe1glQXSYL6SPQ8uC/jvVKV99zkGEizxqlLgm/U5hY/ONVpSNlbcv6olNLhhbcdm+9K3LTiRIvyr5ip1+t7pTo7JQjJwH+EjrQDZcUSA6Y9w/q7FfxEbZbX16GTGn2VLd4q/xoge997/3yzUHGuoNCwNjGzYxs3i1+nLmBR6PzklJ5AqjWK5Ca8h1ClskpFUllwtp1+6mdcX987VpFnNRNsId8o8fLJNRllD43SlDr8lTZM1XvaJXX5lAByYcJY9fDi0OK0Doo4HYDHBaMxT208aODjM3rFNT4M0RoftGHACZnY41CovkcPNmSV8FjHaf2v2zCHuPxiB/Ur0sRyAf6N2YH73BKMYEc=
  # DOCKER_USERNAME
  - secure: UUDx/9eScclSn/8LdTPgliXMEXIyCmz//iZ5XWhbXzF6udHfMdhsBUF0HAqoimdPzeW3wleVl+89zMdnqsrlteBc2pE1FpGnfV2GKI7oloHttumsyHdF7C2ERI0npjqQAnNI4KakPpbF18hYGE9fsKsmwq5kgJLO6Vh4MIQhBB7ue6easFOKfk2pTBMUb4ndWCNQ/D80L7dCAzpCT5pVlY0+gnoF4NghlmXl47Tot3rhoX5WQOW8fhKFAEaAd5KRyqBB8f17OvvwwpB5efYQhkgIhp5gpeskNLGiIfrXvpHR9Rp2OLNVx7UosnNW3aXSuqXF1v316PaRGe3AF3FxM+hLDHsmTx/PgFGdt0gjslmZqdFTAwuM/VVmwte40em8DWO+9WfBv/UAqqEkkfmseuB5w9B3s1/4mDFpCSdKrCrHSqyptdmtHp9gD1pYuKI0WHJ9BXwF49Pp6Y5otILdxzctweFX7bXtJnGqGJERwXhKuLnR9se8wYJBnkTCb3ldspAWG4SSQFaNgcxRmNd8zcOmlqjKtNJoVpAbHwWIJpXeTkY8hFdxoYytUH5N9uD3P2hP3p19c0NYXC7hoZQcKCTo9fv1r6QGa3gCy+lPKbev1S3loqFhdi6C3uc2kvvKlv/DX9xXU3ZV3eBXd7YTP2LV5Wn/IxAnE7s1FfxmTtw=
  # DOCKER_PASSWORD
  - secure: Miau/+R9k0htq7f4vL4SdUQkLQbsM3IH8SlrrCjMUvrqU43Hbd5cQtG52ElgjE16T2fiGFCreabEuQi4zPbEehgWUTM5NKBfEb7VoBPMmItQxGopTiYNYkQ3SVwj+sYgvqFx31xtJmxIxnPnn9JfLstH1roYCZGcP8dYk+S72PG/cdnHW4nX2xVDiXefAokelQqdGSqphY3WI+fo81nXtKjIBBsqcXRuCSOYIXZEaGdvGtRg9Q8espXkZQICn6gd1BilQIE7iKZd/+VDc0RzwM4wwIQOxwFYM/eruZyagLMYOPw26I6WO3zONkDLGrj2n2iqBT/mKxPkVX7nNB2H8IxAG7V3KAA/hprPUJnSGAc0d4jvSTBfhTy6f8LjMZrJr1Vkm4VHk80ysVrd+vSq7lGRepm6al8YPQlbu85xbtJ40Un5Y5cHdR0wcLgto3Lui12OOUTka4xbGn0zfS+aukQZHXlHa2F5uoQhOx51erhptoIiIOZwqwOXbUa2bGw1XRV9tkYLcRkPYZgXMan1RHIxj9YTxCPKRjOVd6LDju67GKHE50Ru3n7Ypk1LIdmxYRQHCe1iACVeMPMHVvqjl65Vdc2M4ylz62/KRCfvpBA9ZAYb4wEMC3rUtOhCO0jcT8Gmjfn/xaogaZzFA/9/HrJzO2KyTK6UHJnb7JdKmEc=
script:
  - cd ${TRAVIS_BUILD_DIR}/${IMAGE} && make build 
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - cd ${TRAVIS_BUILD_DIR}/${IMAGE} && make publish

branches:
  only:
  - master
