sudo: required
language: python
python:
- 3.5
before_install:  
  - sudo apt-get update
  - sudo apt-get install docker-engine
install: pip install --upgrade pip && pip install -r requirements.txt
services:
- docker
env:
  matrix:
  - SERVICE=alpine
  - SERVICE=jenkins-master
  - SERVICE=jenkins-slave
  global:
  - secure: R4Ou6Dgz/XlZdasB7OHLmqIb+XCTLvoahOaHwj61m+uF+Bc3csX36EFhh+FeLXFiqrjvT8JdHnVnxyS1a9A6poP2xY3dyKINICqN63VDXHjpX7KLEs5D+FnrlzXC2EMfbOnvlEqtAB93xNBIsPOzkawmBPBLuy3vvXETpIx3wtOD6Q4BSW06Rl6TaLOc2pECv3+rOpd6mSpR2RrpqGMX5cetqJ/qwbVex9lDlttTv6fJezygzWWIl4XoUJUgzhz1przcbWcQD/hGd7tMohYWSchZRGQeip9mVr6jFqaPH8TggQtxfDQbSmDWx3YCThVyKxmLb8DlPOSsAC2JnvpSkJ7rnjhH0HxyHpMKrzamreAKE6ouDE9D0DdY17ZUzpTE8tAHyG72uWgjoeoJB91ENuCqy7q+x5tg2js++u7zeUcFtG1M3PzK1yw4vxRlXQmlsDlf6jCnUn/0D7zJTs1uVhMy9sz2s+BttspM074hkyOCB5XPmvZs2u32l+/jc5d32H01wor6IJBsUQnRkMCjGA8XAS3Y+k4dG/ncuL8M/Jr/Ft0+heC/8/R8DxNzte9lmNUpl5s+CnvfgEUxCt+lmK6MYP+8AlswIUj2/vXTkgPNn2/Xy3tbywLab+q79qf2lJMMqHsrlAmhPKUT+bXAeXshaGPk16hmZjbmiFJIg2Q=
  - secure: cDcghXoHt5XRf5ykCPI9GNDgIhVdA53gJH+IPuB290fiedveZXQZeW3jSTM6i0XQFva9pH1krMr2wPf2CxSuFuTTko+y/MaowHQvz/4IVy62ZhJfHiAVzhEDTqksXe2BQjFjeLmQZX0GByS/zYsHlsKXvs/hyexCcb8CBldQv9TKxGVistdtuf3INn+qO7nXifwBfCaN6Z7Ery+U+QZ9iZCLuadG2Mmm8RhSx5QzXudMjoNpTO9kgNLaCmN0Bw1SvwBouhM/cw/BmsZBaYWEU0HldkbdJ712kFC2eY1MwqS1+kkc9/VOtVeLbqvzm335qIH4WzQbMYmbLE3peF7mEON/EkmmxRD1ZR4zSvOH80G5VqGquAT5gzxMvxaNLtKlndStZ5UsufZVrimnlgtyCuWQKoplkGeWeN6lV1MnBJCgxvYSWmAjmyO+fHvR/PMUVpQkWwPd7Wp2aLXn5cEfQx21BPIVc3kPOYi4EpebuCHePgrijzPlxnsiVO2fbM1F3bKjBBI47+BMobyup2sd9ZcX5y+I+ICOIuGzObPx5QgKfhg3R9TG1xAbmNEi3WH2xx7UyTlF3rAnukUBxc79vtck5PG50he968t1+R6GqXz1jpZRRwPTJ6a59UH8pGx49Btl93+LnrHESzcCc+56mu50gR1SJKhFeLiMbbBPgBo=
  - secure: JRQYSfXdH997zCfWnrKTuPCOhitKqVVyMYrSRQ/9AE4el1iz35/0tFPd76bJZgbo8wuX2fleGnIZziV2aSFkBcoFoVyQDt7W/grJ+kMgBAZLpqf9y8v8bGAU8vUjnMsnZOI4y8ryXeDtyEdyRkJr1dE9awBXRWRTrPkApxRfYzSDMPZOVB50jtDs/rSi63gJEmE6msPxu5i5YF5esR3sdkBia8A8b/hBGRZgAW+G/qv9QO87GZRB6zywxsW2d36Om8s4GgsitTfQBgvAIxnQeHdfU87tQO6gbsrvGRNrYboEUDYSkE5t/OztDyNsjxPmfy7pePq8z3eiXiiK7FzavgiQGT3gxHYVKLKfLchJqB3V2+zWXHVIaVjrACqZQ5Eq8Ibsy1xusfgdfRvQ9PCcnP3nDPfMarWmgPJbUZt2s9x5i9RlVlboRz3WlyYx98NmKjxsvPzUp8fyk7QfoWK/Z2Ep8C8cPUsfg6W5QnVpGhD4xo87D58UcT6hVZrRptIpgUGDL4px1l5qKLtchpOPzMXPmu0srXWZ8eP3ywzesTXNdUSc6RyUA0sor0P22rITxMg+x/NkiEp7pvS9vNveHYqTHHF/J+senVF3YwHAst03jjRB6zM9khRQ2vrelkCxSB8I0bykmJr/KshoXzZLS6tVV6DIOpBWd9739GFVsfo=
  - CI=True
script:
- python --version
- docker --version
- invoke build $SERVICE
branches:
  only:
  - master
